import {Raleway} from "next/font/google"
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const raleway = Raleway({subsets: ["latin"]});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${raleway.className}, bg-color3`}>{children}</body>
    </html>
  );
}
